#!/usr/bin/env bash
#script for installation and setting up of Nginx

# Update the package list
sudo apt-get -y update

# Install Nginx
sudo apt-get install -y nginx

#ensure Nginx is listening at port 80
sudo ufw allow 'Nginx HTTP'

#To set up a default page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Restrt ninx without using systemctl
sudo service nginx restart
